### ISSUE TITLE
十连单抽等命令会在发送图片后自动撤回

### ISSUE THREAD

**Issue by YsKiKi** [Nwflower/Gacha-plugin#2]
管理员在私聊#喵喵更新后出现的情况

**Comment by Nwflower** [comment]
提供一下yunzai版本号和插件版本号，另外检查一下云崽自带的抽卡是否也会存在撤回情况，如有报错请提供一下报错日志

**Comment by YsKiKi** [comment]
Yunzai版本3.0.0，gasha版本1.2.1，Yunzai自带抽卡未撤回

**Comment by YsKiKi** [comment]
刚刚测试了Yunzai自带抽卡也有撤回现象😭

**Comment by Nwflower** [comment]
已经了解，我将在下一个版本中针对3.0移除关于抽卡判定的自动撤回机制

**Comment by Nwflower** [comment]
既然自带抽卡存在撤回，则不是插件本身的问题，你可以在云崽自带的配置文件中关闭撤回

**Comment by YsKiKi** [comment]
Yunzai自带的配置文件在哪🤔

**Comment by Nwflower** [comment]
对于v3，其配置文件应该在在plugins/genshin/config的yaml格式文件里，如未找到，建议你加群询问。

**Comment by YsKiKi** [comment]
谢解答
