### ISSUE TITLE
#抽卡设置卡池同步出错

### ISSUE THREAD

**Issue by ImHeroZero** [Nwflower/Gacha-plugin#3]
0|Yunzai  | [2022-09-08T21:58:07.583] [MARK] [私聊][Zero(1563873716)] #抽卡设置卡池同步:sysCfg
0|Yunzai  | [2022-09-08T21:58:07.586] [ERRO] plugin_Gacha-plugin.sysCfg
0|Yunzai  | [2022-09-08T21:58:07.587] [ERRO] TypeError: Cannot read properties of undefined (reading 'join')
0|Yunzai  |     at Module.sysCfg (file:///c:/App/Yunzai-Bot/plugins/Gacha-plugin/apps/admin.js:206:47)
0|Yunzai  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
0|Yunzai  |     at async Object.dealMsg (file:///c:/App/Yunzai-Bot/lib/dealMsg.js:234:19)

admin.js:206
读的gacha.json里面没有join方法前面那个标签
并且报错后gacha.json可能没写完,导致所有抽卡操作都报错了

**Comment by Nwflower** [comment]
建议尽快升级V3

**Comment by ImHeroZero** [comment]
> 

想问下V2版本不更新嘛?现在用的插件Readme都写着V3不稳定来着,而且自己也放了不少v2时期的js,我就没有升.
这下不升不行了.

**Comment by Nwflower** [comment]
V3没有不稳定的说法，并且现在也有很多插件；V2版本bug稍后会修复，预计24小时以内。
